### ISSUE TITLE
some kinda mediocre prompt

### ISSUE THREAD

**Issue by hawkw** [hawkw/mycelium#360]
it would be cool if you could type stuff into mycelium and get text back out. maybe eventually you could even run "commands".

this probably means the following:

- [x] **actual keyboard driver** (see #358)
- [ ] **reserve a line at the bottom of the framebuffer for the text the user is typing**, and don't write logs there
- [ ] **when scrolling logs, don't scroll that line**. this is gonna be mildly annoying --- we probably want to change the logging code to write text to a text buffer, and use that to draw a screen, rather than scrolling the raw pixels.  this would also let us scroll history.. (see #364)
- [x] **put keyboard text in a buffer** and draw it, and clear it on carriage returns (eventually this could "run" a "command")
- [x] **actually add some shell commands**: see #374
